### ISSUE TITLE
Criar modelagem

### ISSUE THREAD

**Issue by DanielKepler** [carvalhoiago/Black-Flag#1]

**Comment by DanielKepler** [comment]
Pelo dbdiagram fazer a modelagem

**Comment by carvalhoiago** [comment]
`Table User{
  id int [pk]
  photo file
  email email [unique]
  password varchar
  type varchar
}

Table User_library {
  id int [pk]
  user_id int
  game_id int
}

ref: User_library.user_id > User.id
ref: User_library.game_id > Game.id

Table Game {
  id int [pk]
  price float
  publisher_id int
  description text
  trailer file
}

ref: Game.publisher_id > Publisher.id

Table Genre {
  name varchar [pk]
}

Table Publisher {
  id int [pk]
  name varchar
}

Table Game_image {
  id int [pk]
  game_id int
  image file
}

ref: Game_image.game_id > Game.id

Table Game_genre {
  id int [pk]
  genre_id int
  game_id int
}

ref: Game_genre.genre_id > Genre.name
ref: Game_genre.game_id > Game.id`
